// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqaePqqquK883E4NmE-iyB-rpYMm3qc8E',
    appId: '1:1027153706332:web:9aa0faf2673b8d8ec95599',
    messagingSenderId: '1027153706332',
    projectId: 'impression-gallery-e99fa',
    authDomain: 'impression-gallery-e99fa.firebaseapp.com',
    storageBucket: 'impression-gallery-e99fa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGP4dVBQCgjs0zxvLsGGBmQzT4nUNU6pI',
    appId: '1:1027153706332:android:8b678bee12fa61b8c95599',
    messagingSenderId: '1027153706332',
    projectId: 'impression-gallery-e99fa',
    storageBucket: 'impression-gallery-e99fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkDrBHTaKF-lBvsHggW8D0OGCD9gHqcis',
    appId: '1:1027153706332:ios:396e98b9175dc2b5c95599',
    messagingSenderId: '1027153706332',
    projectId: 'impression-gallery-e99fa',
    storageBucket: 'impression-gallery-e99fa.firebasestorage.app',
    iosBundleId: 'com.example.impressionGallery',
  );
}
